import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '빼곡 : 빼곡하게 채우는 나만의 책장',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased m-0`}>{children}</body>
    </html>
  );
}
